from __future__ import annotations

from typing import Type, Any
from pydantic import BaseModel
import ollama

class OllamaChatModel:
    """Ollama adapter."""

    def __init__(self, model: str, temperature: float = 0.1) -> None:
        self.model = model
        self.temperature = temperature

    def generate(
        self,
        messages: list[dict[str, str]],
        response_format: Type[BaseModel] | None = None
    ) -> str:
        kwargs: dict[str, Any] = {
            "model": self.model,
            "messages": messages,
            "options": {"temperature": self.temperature},
        }

        # If a Pydantic model is provided, extract its schema and pass it to Ollama
        if response_format:
            kwargs["format"] = response_format.model_json_schema()

        response = ollama.chat(**kwargs)
        return response["message"]["content"]

    def generate_stream(self, messages: list[dict[str, str]]):
        """Yields chunks of text as they are generated by Ollama."""
        kwargs = {
            "model": self.model,
            "messages": messages,
            "options": {"temperature": self.temperature},
            "stream": True,
        }

        for chunk in ollama.chat(**kwargs):
            if "message" in chunk and "content" in chunk["message"]:
                yield chunk["message"]["content"]

def build_chat_model(config: dict) -> OllamaChatModel:
    provider = config["provider"]

    if provider == "ollama":
        return OllamaChatModel(
            model=config["model"],
            temperature=float(config.get("temperature", 0.1))
        )

    raise ValueError(f"Unsupported LLM provider: {provider}")